version: "3.9"

services:
  product:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: product-service

    depends_on:
      - postgres

    ports:
      - "8080:8080"

    env_file:
      - .env

    restart: unless-stopped

  postgres:
    image: postgres:17

    container_name: product-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

volumes:
  postgres_data:
